"""initial schema

Revision ID: bfd7445aae54
Revises: 
Create Date: 2026-07-17 20:39:52.686452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd7445aae54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposit_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('derivation_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('chain', 'derivation_index', name='uq_deposit_address_chain_index')
    )
    op.create_table('hot_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('derivation_path', sa.String(length=64), nullable=False),
    sa.Column('balance_cache', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain')
    )
    op.create_table('swap_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_token', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('client_name', sa.String(length=256), nullable=True),
    sa.Column('client_email', sa.String(length=256), nullable=True),
    sa.Column('client_date_of_birth', sa.String(length=32), nullable=True),
    sa.Column('client_country', sa.String(length=256), nullable=True),
    sa.Column('deposit_address_id', sa.Integer(), nullable=True),
    sa.Column('from_chain', sa.String(length=16), nullable=False),
    sa.Column('from_asset', sa.String(length=16), nullable=False),
    sa.Column('from_amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('deposit_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('to_chain', sa.String(length=16), nullable=False),
    sa.Column('to_asset', sa.String(length=16), nullable=False),
    sa.Column('to_amount_quoted', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('to_amount_payout', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('to_amount_quoted_gross', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('to_amount_executed', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('margin_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('quote_id', sa.String(length=128), nullable=True),
    sa.Column('quote_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quote_raw_response', sa.JSON(), nullable=True),
    sa.Column('swap_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('requires_treasury_rebalance', sa.Boolean(), nullable=False),
    sa.Column('withdrawal_address', sa.String(length=128), nullable=True),
    sa.Column('withdrawal_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('wallet_ownership_challenge_id', sa.String(length=64), nullable=True),
    sa.Column('wallet_ownership_challenge_message', sa.Text(), nullable=True),
    sa.Column('wallet_ownership_verification_id', sa.String(length=64), nullable=True),
    sa.Column('screening_decision', sa.String(length=16), nullable=True),
    sa.Column('screening_score', sa.Float(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deposit_address_id'], ['deposit_addresses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_token')
    )
    with op.batch_alter_table('swap_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swap_orders_status'), ['status'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swap_order_id', sa.Integer(), nullable=True),
    sa.Column('account', sa.String(length=128), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('entry_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['swap_order_id'], ['swap_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_entries')
    with op.batch_alter_table('swap_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swap_orders_status'))

    op.drop_table('swap_orders')
    op.drop_table('hot_wallets')
    op.drop_table('deposit_addresses')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
